baisc Subsystem set up with if else flow
Valor6800/FRC-6800-2022-code pull request #8
Opened 2022-01-18 00:38 UTC by AntarcticaByToto

2022-01-18 00:42 UTC, AntarcticaByToto commented
Set up code structure for feeder subsystem.

2022-01-19 23:15 UTC, mray190 requested changes
See comments below

2022-01-19 23:15 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Feeder.cpp
> +    // @TODO Reverse speed set via dashboard
Use smart dashboard to set some speeds

2022-01-19 23:15 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Feeder.cpp
> +    // @TODO set variables for the speeds instead of calling set every if statement
Set variables for the speeds, call set at the end of the function

2022-01-22 03:46 UTC, closed without merging